geomorphs : ../assets/H.svg ../assets/H1.svg ../assets/F.svg ../assets/T.svg ../assets/P.svg

clean :
	rm ../assets/H.svg ../assets/H1.svg ../assets/F.svg ../assets/T.svg ../assets/P.svg

../assets/H.svg : tile1.svg
	inkscape -l -o ../assets/H.svg tile1.svg

../assets/H1.svg : tile1.svg
	inkscape -l -o ../assets/H1.svg tile1.svg

../assets/F.svg : tile1.svg
	inkscape -l -o ../assets/F.svg tile1.svg

../assets/T.svg : tile1.svg
	inkscape -l -o ../assets/T.svg tile1.svg

../assets/P.svg : tile1.svg
	inkscape -l -o ../assets/P.svg tile1.svg

