geomorphs : ../assets/tile1.svg ../assets/tile2.svg ../assets/tile3.svg ../assets/tile3a.svg

clean :
	rm ../assets/tile1.svg ../assets/tile2.svg ../assets/tile3.svg ../assets/tile3a.svg 

../assets/%.svg : %.svg
	inkscape -l -o $@ $<
